version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
    networks:
      - my_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - my_network

  webapp:
    image: nginx
    hostname: webapp
    networks:
      - my_network
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    command:
      - -nginx.scrape-uri=http://webapp/nginx_status
    ports:
      - "9113:9113"
    depends_on:
      - webapp
    networks:
      - my_network

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - my_network

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    networks:
      - my_network

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - my_network

networks:
  my_network:
