name: Docker CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Docker и Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      - name: Сборка контейнеров
        run: docker-compose build

      - name: Запуск контейнеров
        run: docker-compose up -d
