name: Docker CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Check Docker version
        run: docker --version

      - name: Build & Run
        run: |
          sudo docker compose version || sudo docker-compose version
          sudo docker-compose up -d --build
